# -*- coding: utf-8 -*-
"""lifani.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BFa5BNiZYx8GKXsKbLd4eLnKyL2EoeHE
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import joblib

# Standardisasi Direktori Absolut Google Drive
WORKSPACE_PATH = ""

def run_preprocessing(input_path=WORKSPACE_PATH + "dataset.csv"):
    print(f"Memulai proses preprocessing pada direktori: {input_path}")

    # 1. Ingesti Data
    df = pd.read_csv(input_path)

    # 2. Pembersihan Data (Penghapusan Null & Duplikat)
    df = df.dropna().drop_duplicates()

    # 3. Dekomposisi Fitur dan Target
    X = df.drop(columns=['Target'])
    y = df['Target']

    # 4. Encoding Target Kategorikal
    encoder = LabelEncoder()
    y_encoded = encoder.fit_transform(y)

    # 5. Pemisahan Data Latih dan Data Uji (Rasio 80:20)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
    )

    # 6. Standarisasi Distribusi Matriks Skalar
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # 7. Ekspor Data Siap Latih ke Google Drive
    output_path = WORKSPACE_PATH + "data_siap_latih.pkl"
    joblib.dump((X_train_scaled, X_test_scaled, y_train, y_test, encoder), output_path)
    print(f"Preprocessing Selesai. Data berhasil diamankan secara persisten ke: '{output_path}'")

if __name__ == "__main__":
    run_preprocessing()