# -*- coding: utf-8 -*-
"""lifani.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BFa5BNiZYx8GKXsKbLd4eLnKyL2EoeHE
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import joblib
import os

# Deteksi otomatis jalur absolut server GitHub Actions
WORKSPACE = os.getenv("GITHUB_WORKSPACE", ".")

def run_preprocessing():
    input_path = os.path.join(WORKSPACE, "dataset.csv")
    print(f"Memulai proses preprocessing pada direktori: {input_path}")
    
    df = pd.read_csv(input_path)
    df = df.dropna().drop_duplicates()
    
    X = df.drop(columns=['Target']) 
    y = df['Target']
    
    encoder = LabelEncoder()
    y_encoded = encoder.fit_transform(y)
    
    X_train, X_test, y_train, y_test = train_test_split(
        X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
    )
    
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    
    # Ekspor ke jalur absolut agar tidak hilang oleh isolasi MLflow
    output_path = os.path.join(WORKSPACE, "data_siap_latih.pkl")
    joblib.dump((X_train_scaled, X_test_scaled, y_train, y_test, encoder), output_path)
    print(f"Preprocessing Selesai. Data diamankan ke: '{output_path}'")

if __name__ == "__main__":
    run_preprocessing()
