# -*- coding: utf-8 -*-
"""modelling_tuning.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uA2v-Q7dOCowo4KmIM5p9uzEHKBZPkLq
"""

import mlflow
import mlflow.sklearn
import dagshub
import joblib
import os
import shutil
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

DAGSHUB_USERNAME = "pedro-muqoyat"
DAGSHUB_REPO = "Eksperimen_SML_lifani"

# Deteksi otomatis jalur absolut server GitHub Actions
WORKSPACE = os.getenv("GITHUB_WORKSPACE", ".")

def train_and_log_model():
    print("Memuat matriks data siap latih...")
    data_path = os.path.join(WORKSPACE, "data_siap_latih.pkl")
    X_train_scaled, X_test_scaled, y_train, y_test, encoder = joblib.load(data_path)
    
    dagshub.init(repo_owner=DAGSHUB_USERNAME, repo_name=DAGSHUB_REPO, mlflow=True)
    mlflow.set_tracking_uri(f"https://dagshub.com/{DAGSHUB_USERNAME}/{DAGSHUB_REPO}.mlflow")
    mlflow.set_experiment("Eksperimen_Prediksi_Status_Akademik")
    
    base_model = RandomForestClassifier(random_state=42)
    param_space = {
        'n_estimators': [50, 100],
        'max_depth': [10, None],
        'class_weight': ['balanced'] 
    }
    grid_search = GridSearchCV(estimator=base_model, param_grid=param_space, cv=3, scoring='accuracy', n_jobs=-1)
    
    with mlflow.start_run(run_name="Eksperimen_RandomForest_V2"):
        grid_search.fit(X_train_scaled, y_train)
        
        best_model = grid_search.best_estimator_
        predictions = best_model.predict(X_test_scaled)
        
        final_accuracy = accuracy_score(y_test, predictions)
        final_f1 = f1_score(y_test, predictions, average='weighted')
        
        mlflow.log_params(grid_search.best_params_)
        mlflow.log_metric("akurasi_pengujian", final_accuracy)
        mlflow.log_metric("f1_score_bobot", final_f1)
        mlflow.sklearn.log_model(best_model, "model_klasifikasi_mahasiswa")
        
        cm = confusion_matrix(y_test, predictions)
        plt.figure(figsize=(6, 4))
        sns.heatmap(cm, annot=True, fmt='d', cmap='Oranges',
                    xticklabels=encoder.classes_, yticklabels=encoder.classes_)
        plt.title('Matriks Evaluasi Prediksi Model')
        plt.ylabel('Status Aktual')
        plt.xlabel('Hasil Prediksi')
        
        # Ekspor artefak visual ke ruang kerja absolut
        graph_filename = os.path.join(WORKSPACE, "evaluasi_confusion_matrix.png")
        plt.savefig(graph_filename, bbox_inches='tight')
        mlflow.log_artifact(graph_filename)
        plt.close()

        # Ekspor arsitektur model lokal ke ruang kerja absolut untuk dibungkus Docker
        local_model_dir = os.path.join(WORKSPACE, "local_model_dir")
        if os.path.exists(local_model_dir):
            shutil.rmtree(local_model_dir)
        mlflow.sklearn.save_model(best_model, local_model_dir)
        
        print("\nSiklus Pelatihan Selesai.")

if __name__ == "__main__":
    train_and_log_model()
