name: Data Preprocessing Pipeline

on:
  push:
    branches:
      - main # (Atau ganti 'master' jika branch Anda bernama master)

jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Mengunduh Kode Repositori
        uses: actions/checkout@v3

      - name: 2. Konfigurasi Python Lingkungan
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: 3. Instalasi Dependensi Data
        run: |
          pip install pandas scikit-learn

      - name: 4. Eksekusi Skrip Otomatisasi
        run: |
          python preprocessing/automate_lifani.py
