name: Data Preprocessing Pipeline

on:
  push:
    paths:
      - "dataset.csv"
      - "preprocessing/automate_*.py"
      - ".github/workflows/preprocessing.yml"

jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Mengunduh Kode Repositori
        uses: actions/checkout@v3

      - name: 2. Konfigurasi Python Lingkungan
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: 3. Instalasi Dependensi Data
        run: |
          pip install pandas scikit-learn

      - name: 4. Eksekusi Skrip Otomatisasi (Bypass Interaksi Manual)
        run: |
          # Perintah ini akan menjalankan skrip Kriteria 1 Anda
          # dan memastikan tidak ada error pada arsitektur pipeline data
          python preprocessing/automate_Nama-siswa.py
